//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGame.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenutzerProfil
    {
        public int ID { get; set; }
        public int FKBenutzer { get; set; }
        public string CharcterName { get; set; }
        public string Prefabname { get; set; }
        public string TopName { get; set; }
        public string BottomName { get; set; }
        public string ShoesName { get; set; }
        public Nullable<System.DateTime> LastPlay { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
    }
}
