//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGame.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Benutzer()
        {
            this.BenutzerProfil = new HashSet<BenutzerProfil>();
            this.BenutzerSettings = new HashSet<BenutzerSettings>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Passwort { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IstFreigeschalten { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenutzerProfil> BenutzerProfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenutzerSettings> BenutzerSettings { get; set; }
    }
}
