//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGame.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenutzerSettings
    {
        public Nullable<int> IDSettings { get; set; }
        public double Audio { get; set; }
        public int Graphic { get; set; }
        public string Resoultion { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
    }
}
